# Name of your site (displayed in the header)
name: Prometheus
# Short bio or description (displayed in the header)
description: Web Developer and Tech Enthusiast

# URL of your avatar or profile pic (GitHub profile picture URL or any image link)
avatar: https://avatars.githubusercontent.com/yourusername

# Footer social links (only fill in what you use)
footer-links:
  github: Prometheus
  linkedin: your-linkedin-username
  twitter: your-twitter-handle
  email: your@email.com
  rss: rss
  youtube: user/yourchannelname

# Enable Disqus (optional – set up a free Disqus account first)
disqus:

# Google Analytics (optional – use your tracking ID)
google_analytics:

# Your website URL (replace with your GitHub username)
url: https://prometheus.github.io

# Only needed if using a subfolder for a project site
baseurl: ""

markdown: redcarpet
highlighter: pygments
permalin
